### ISSUE TITLE
Feature Request: Support Lifecycle Hooks in appspec

### ISSUE THREAD

**Issue by tvandewalle** [cdklabs/cdk-ecs-codedeploy#139]
The current EcsAppSpec class does not support lifecycle hooks (see: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-ecs). Some of the functionality of lifecycle hooks can be covered by alarms or the ApiCanary class, however this doesn't cover all possible use cases. One primary use case that I can think of is in a Blue/Green deployment being able to run a smoke test on the new task version prior to accepting any production traffic would be useful.

Would be happy to contribute if there is perceived value here. Thanks.

**Comment by cplee** [comment]
This would be awesome to have added to the construct @tvandewalle. Your contribution would be much appreciated!

**Comment by mikeshepherd** [comment]
This is a change that I've been sat on for a while but have been unable to get round to testing it fully yet. But it's time has now come and I should be able to confirm if my changes are correct in the next day or two.
I've raised a PR to save you from duplicating the work, but right now it's buyer beware. I'll post an update once I know it works.
