### ISSUE TITLE
Synthetic Canary Runtime Deprecated

### ISSUE THREAD

**Issue by tramo-usg** [cdklabs/cdk-ecs-codedeploy#463]
https://github.com/cdklabs/cdk-ecs-codedeploy/blob/622c1f7bc553ae51858e21c4d652d42db6bb43c8/src/api-canary/index.ts#L226C24-L226C55
this canary version `runtime: Runtime.SYNTHETICS_NODEJS_PUPPETEER_4_0,` is deprecated
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html#CloudWatch_Synthetics_Canaries_runtime_support, please upgrade to a supported synthetic runtime

**Comment by KevinDing1** [comment]
**https://github.com/cdklabs/cdk-ecs-codedeploy/blob/eed5fc61c39416626749c93941faa4a75261fc52/src/api-canary/index.ts#L226**

Has been updated
